### ISSUE TITLE
biome:name does not work!

### ISSUE THREAD

**Issue by AshiroKun** [Arthed-Studios/CustomBiomeColors#4] opened 2022-01-07 21:08 UTC
Minecraft version: 1.17
Server version: PaperMC 1.17
Plugin Version: 1.0.1
Issue:
If I try to name the biome with "biome:name" placeholder it ends up saying "an internal error has occured whilst performing this command" and spams the console.

I am able to use the plugin without entering a biome name but I want to be able to add a biome name as the randomly generated biome name is messy and does not make sense.

`[22:01:45 INFO]: Ashikki issued server command: //setgrasscolor #242424 biome:Decay
[22:01:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command '/setgrasscolor' in plugin CustomBiomeColors v1.0.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2344) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2155) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2136) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.minecraft.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: biome:Decay
        at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[app:?]
        at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[app:?]
        at me.arthed.custombiomecolors.nms.NmsServer_1_17.doesBiomeExist(NmsServer_1_17.java:42) ~[CustomBiomeColors-1.0.1.jar:?]
        at me.arthed.custombiomecolors.commands.SetBiomeColorCommand.onCommand(SetBiomeColorCommand.java:62) ~[CustomBiomeColors-1.0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
        ... 21 more`

**Comment by Styro457** [comment] 2023-09-07 05:28
Duplicate of #3

**Closed by Styro457** 2023-09-07 05:28 UTC
Labels: enhancement, good first issue
